Added detection of commits no longer existing in the event store
liquidprojections/LiquidProjections.NEventStore pull request #3
Opened 2017-06-02 13:08 UTC by dennisdoomen

Includes upgrading the API to LiquidProjections 2.0, which is a breaking change here as well.

2017-06-02 14:13 UTC, IharBury requested changes

2017-06-02 14:13 UTC, IharBury commented on .vs/config/applicationhost.config
> +<?xml version="1.0" encoding="UTF-8"?>
Why do we need this file?

2017-06-02 14:13 UTC, IharBury commented on Tests/LiquidProjections.NEventStore.Specs/NEventStoreAdapterSpecs.cs
>                      A.CallTo(() => eventStore.GetFrom(A<string>.Ignored)).Returns(new[] {The<ICommit>()});
Why would the event store return a commit that is earlier than the requested checkpoint?

2017-06-06 13:47 UTC, dennisdoomen commented
@IharBury please re-review

2017-06-07 07:19 UTC, IharBury reviewed
Some minor remarks left

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/EnumerableExtensions.cs
> +        public static IReadOnlyList<T> ToReadOnly<T>(this IEnumerable<T> items)
Maybe it's better to call it `ToReadOnlyList` since `IEnumerable<T>` is already read-only.

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/NEventStoreAdapter.cs
> +    /// </summary>
And also it's important that this adapter is designed to avoid multiple parallel requests to the NEventStore.

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/NEventStoreAdapter.cs
> +        /// The amount of time to wait befor polling again after the event store has not yieled any transactions anymroe.
Typos: "befor", "yieled", "anymroe".

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +#endif
Maybe it's better to move this logging into the `TryGetNextPage` method.

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +                // Just continue the next iteration
Should we log the exception at least?

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +                            .ToReadOnly();
This can slow things down a bit. Can we do this for the first request only?

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +            while (!cancellationTokenSource.IsCancellationRequested)
Maybe it makes sense to split this loop so that the ahead detection logic does not interfere with the usual operation.

2017-06-07 07:19 UTC, IharBury commented on Src/LiquidProjections.NEventStore/NEventStoreAdapter.cs
> +                throw;
By returning an empty page we also reused the polling interval mechanism. Now when we just throw, we will retry immediately. Not sure if it's good or bad.

2017-06-07 07:19 UTC, IharBury commented on Tests/LiquidProjections.NEventStore.Specs/NEventStoreAdapterSpecs.cs
> +                    }, "someId");
We are not reliably testing the polling interval logic here

2017-06-07 07:19 UTC, IharBury commented on Tests/LiquidProjections.NEventStore.Specs/NEventStoreAdapterSpecs.cs
> +                ;
typo

2017-06-07 11:43 UTC, dennisdoomen commented on Src/LiquidProjections.NEventStore/NEventStoreAdapter.cs
> +                throw;
Is probably fine. In the future we may even decide to add some progressively increasing delay.

2017-06-07 11:48 UTC, dennisdoomen commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +                // Just continue the next iteration
Already happens in the underlying adapter, just before the `throw`.

2017-06-07 11:49 UTC, dennisdoomen commented on Tests/LiquidProjections.NEventStore.Specs/NEventStoreAdapterSpecs.cs
> +                    }, "someId");
It was an existing test. Will look at that another time. Will add a comment.

2017-06-07 13:25 UTC, dennisdoomen commented
Done doing all the rework.

2017-06-07 17:01 UTC, IharBury commented on Src/LiquidProjections.NEventStore/Subscription.cs
> +                // Just continue the next iteration
Yes, but there can theoretically be other exceptions when getting the next page, coming not from the NEventStore. As an alternative, we could wrap the NEventStore exception to our own exception and only catch that one here.

2017-06-07 17:02 UTC, IharBury approved these changes
Other than the minor catch concern everything else is great

2017-06-08 05:01 UTC, merged